name: Cache (GCC, GCC32, Clang)

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone Repo kernel_build_actions
      uses: whyakari/github-repo-action@v3.1
      with:
        owner: 'whyakari'
        repository: 'kernel_build_actions'
        access-token: ${{ secrets.TOKEN_GITHUB }}

    - name: Download Clang18.0.0
      working-directory: ./kernel_build_actions
      run: |
        chmod +x download_clang18.0.0.sh
        ./download_clang18.0.0.sh

    - name: Setup GCC / GCC32 / Clang18
      run: |
        TC_DIR="$HOME/tc/clang-18.0.0"
        GCC_64_DIR="$HOME/tc/aarch64-linux-android-14.0"
        GCC_32_DIR="$HOME/tc/arm-linux-androideabi-14.0"

        if ! [ -d "${GCC_64_DIR}" ]; then
            echo "gcc not found! Cloning to ${GCC_64_DIR}..."
            git clone --depth=1 -b 14 https://github.com/ZyCromerZ/aarch64-zyc-linux-gnu ${GCC_64_DIR}
        fi

        if ! [ -d "${GCC_32_DIR}" ]; then
            echo "gcc_32 not found! Cloning to ${GCC_32_DIR}..."
            git clone --depth=1 -b 14 https://github.com/ZyCromerZ/arm-zyc-linux-gnueabi ${GCC_32_DIR}
        fi

    - name: Cache Create
      id: tc-cache
      uses: actions/cache/save@v3
      with:
        path: /home/runner/tc
        key: ${{ runner.os }}-tc

    - name: Display cached directories
      run: |
        ls -R $HOME/tc/
