name: Build Kernel (KSU) Fourteen

on:
  workflow_dispatch

env:
  ZIPNAME: MoeKernel-$(date '+%Y%m%d-%H%M').zip
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Repo Kernel
        uses: whyakari/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'fourteen'
          owner: 'whyakari'
          repository: 'kernel_moe_pixelos'
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Github set Config Email and Name
        working-directory: ./kernel_moe_pixelos
        run: |
          git config --global user.email "akariondev@gmail.com"
          git config --global user.name "ginkgo"
  
      - name: Compile Kernel CI
        working-directory: ./kernel_moe_pixelos
        run: |
          # chmod +x build.sh
          # ./build.sh
          touch a.txt
          zip -r test.zip a.txt

      - name: Artifact Path
        working-directory: ./kernel_moe_pixelos
        run: |
          echo "artifactPath=/home/runner/work/kernel_moe_pixelos/**/*.zip" >> $GITHUB_ENV
          
      - name: Upload Kernel
        uses: actions/upload-artifact@v3
        with:
          name: artifact-kernel
          path: ${{ env.artifactPath }}
          if-no-files-found: error
