name: PixelOS Kernel Build (Fourteen/KSU)

on:
  workflow_dispatch

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
  API_ID: ${{ secrets.API_ID }}
  API_HASH: ${{ secrets.API_HASH }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Repo Kernel
        uses: whyakari/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'fourteen'
          owner: 'whyakari'
          repository: 'kernel_moe_pixelos'
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: /home/runner/tc
          key: ${{ runner.os }}-tc
        id: tc-cache

      - name: Github set Config
        working-directory: ./kernel_moe_pixelos
        run: |
          git config --global user.email "akariondev@gmail.com"
          git config --global user.name "ginkgo"
  
      - name: Install Dependencies
        run: |
         sudo apt-get update
         sudo apt-get -y --no-install-recommends install python3 python3-pip git make gcc bc bison flex libssl-dev ccache libelf-dev libncurses-dev bc binutils-dev ca-certificates clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev

      - name: Pip Install Packages
        working-directory: ./kernel_moe_pixelos
        run: |
          pip install Pyrogram TgCrypto

      - name: Permissions Set
        working-directory: ./kernel_moe_pixelos
        run: |
          chmod +x build.sh ksu_update.sh
  
      - name: Compile Kernel CI
        working-directory: ./kernel_moe_pixelos
        run: |
          python3 upload_bot.py -t dev # or release.
  
